### PR TITLE
Bunch of changes to make the BNO-055 work on my esp8266

### PR DESCRIPTION
**Pull request by ckuethe**

### CODE REVIEW

**Comment by jsonpoindexter** [comment]
Any idea when this will be merged?

**Comment by deshipu** [comment]
I don't think it will.

**Comment by deshipu** [comment]
@ckuethe can you get rid of all the changes that are not immediately related to the problem that you are trying to fix there?

**Comment by deshipu** [comment]
I just pushed some changes taken from the CircuitPython version of this driver, which make it work more reliably. I think they make this pull request obsolete.

**Comment by jsonpoindexter** [comment]
Good to know @deshipu. Thank you for your work!

**Pull request closed without merging**
